FROM alpine:latest

LABEL maintainer="Wolfram Diestel <diestel@steloj.de>"
# adaptita de: https://github.com/madduci/docker-github-pages/blob/master/Dockerfile

# https://pages.github.com/versions/
ARG GITHUB_PAGES_VERSION=204

VOLUME /site

EXPOSE 4000

WORKDIR /site

RUN apk update && \
    apk --update add \
    gcc \
    g++ \
    make \
    curl \
    bison \
    ca-certificates \
    tzdata \
    ruby \
    ruby-rdoc \
    ruby-irb \
    ruby-bundler \
    ruby-dev \
    glib-dev \
    libc-dev && \
    echo 'gem: --no-document' > /etc/gemrc && \
    gem install bundler && \
    gem install github-pages --version $GITHUB_PAGES_VERSION && \
    gem install jekyll-watch && \
    gem install jekyll-admin && \
    apk del gcc g++ binutils bison perl nodejs make curl && \
    rm -rf /var/cache/apk/*

CMD ["exec", "jekyll"]
ENTRYPOINT ["bundle"]
