var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,f):$jscomp.polyfillUnisolated(a,b,c,f))};$jscomp.polyfillUnisolated=function(a,b,c,f){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var k=a[f];if(!(k in c))return;c=c[k]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,f){var k=a.split(".");a=1===k.length;f=k[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var q=0;q<k.length-1;q++){var x=k[q];if(!(x in f))return;f=f[x]}k=k[k.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?f[k]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,k,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[k]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(k):$jscomp.POLYFILL_PREFIX+k,k=
$jscomp.propertyToPolyfillSymbol[k],$jscomp.defineProperty(f,k,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Object.entries",function(a){return a?a:function(b){var c=[],f;for(f in b)$jscomp.owns(b,f)&&c.push([f,b[f]]);return c}},"es8","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(b,c){var f=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var k=f.length,q=b.length;c=Math.max(0,Math.min(c|0,f.length));for(var x=0;x<q&&c<k;)if(f[c++]!=b[x++])return!1;return x>=q}},"es6","es3");$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(k,q){this.$jscomp$symbol$id_=k;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:q})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,f=function(k){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(k||"")+"_"+c++,k)};return f},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var f=$jscomp.global[b[c]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,f=!1,k={next:function(){if(!f&&c<a.length){var q=c++;return{value:b(q,a[q]),done:!1}}f=!0;return{done:!0,value:void 0}}};k[Symbol.iterator]=function(){return k};return k};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(b,c,f){var k=this.length||0;0>c&&(c=Math.max(0,k+c));if(null==f||f>k)f=k;f=Number(f);0>f&&(f=Math.max(0,k+f));for(c=Number(c||0);c<f;c++)this[c]=b;return this}},"es6","es3");$jscomp.typedArrayFill=function(a){return a?a:Array.prototype.fill};
$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
function HTTPRequest(a,b,c,f){var k=new XMLHttpRequest,q=new FormData;c=$jscomp.makeIterator(Object.entries(c));for(var x=c.next();!x.done;x=c.next()){var n=$jscomp.makeIterator(x.value);x=n.next().value;n=n.next().value;q.append(x,n)}k.open(a,b,!0);k.onload=function(){200<=this.status&&400>this.status?f.call(this,this.response):console.error("Eraro dum \u015dargo de "+b)};k.onerror=function(){console.error("Eraro dum konekti\u011do por "+b)};k.send(q)}
function helpo_pagho(a){window.open("https://revuloj.github.io/temoj/"+a)}function ready(a){"loading"!=document.readyState?a():document.addEventListener("DOMContentLoaded",a)}function make_element(a,b,c){a=document.createElement(a);for(var f in b)a.setAttribute(f,b[f]);c&&a.appendChild(document.createTextNode(c));return a}
function make_button(a,b,c){c=void 0===c?"":c;var f=document.createElement("BUTTON");f.appendChild(document.createTextNode(a));f.addEventListener("click",b);c&&f.setAttribute("title",c);return f}function make_icon_button(a,b,c){c=void 0===c?"":c;var f=document.createElement("BUTTON");b&&f.addEventListener("click",b);f.classList.add(a,"icon_btn");c&&f.setAttribute("title",c);return f}
function isLocalLink(a){if("#"==a[0])return!0;var b=getUrlFileName(document.location.pathname);a=getUrlFileName(a);return b==a}function getUrlFileName(a){return a.substring(a.lastIndexOf("/")+1).split("#")[0]}function getHashParts(){var a="#"==location.hash[0]?location.hash.substr(1):location.hash,b={};a=$jscomp.makeIterator(a.split("&"));for(var c=a.next();!c.done;c=a.next())p=c.value,0>p.indexOf("=")?b.mrk=p:(c=p.split("="),b[c[0]]=c[1]);return b}
function getParamValue(a){var b=null,c=[];location.search.substr(1).split("&").forEach(function(f){c=f.split("=");c[0]===a&&(b=decodeURIComponent(c[1]))});return b}function str_repeat(a,b){for(var c="",f=1;f<=b;f++)c+=a;return c}function eo_ascii(a){return a.replace(/\u0109/g,"cx").replace(/\u011d/g,"gx").replace(/\u015d/g,"sx").replace(/\u0135/g,"jx").replace(/\u0125/g,"hx").replace(/\u016d/g,"ux")}
function cxigi(a,b){var c="";b=String.fromCharCode(b);"s"==a?c="\u015d":"\u015d"==a?c="s"+b:"S"==a?c="\u015c":"\u015c"==a?c="S"+b:"c"==a?c="\u0109":"\u0109"==a?c="c"+b:"C"==a?c="\u0108":"\u0108"==a?c="C"+b:"h"==a?c="\u0125":"\u0125"==a?c="h"+b:"H"==a?c="\u0124":"\u0124"==a?c="H"+b:"g"==a?c="\u011d":"\u011d"==a?c="g"+b:"G"==a?c="\u011c":"\u011c"==a?c="G"+b:"u"==a?c="\u016d":"\u016d"==a?c="u"+b:"U"==a?c="\u016c":"\u016c"==a?c="U"+b:"j"==a?c="\u0135":"\u0135"==a?c="j"+b:"J"==a?c="\u0134":"\u0134"==a&&
(c="J"+b);return c};var revo_url="reta-vortaro.de";function nav_toggle(){var a=document.getElementById("navigado");a.style.display=""==a.style.display?"block":""}
function ref_target(a){var b=a.getAttribute("href"),c=a.getAttribute("target");if(b.startsWith("#"))return"int";if(b.startsWith("http://")&&b.substring(6,revo_url.length)!=revo_url||b.startsWith("https://")&&b.substring(7,revo_url.length)!=revo_url)return"ext";if("precipa"==c)return"main";if("indekso"==c)return"nav";if(!c&&(a=a.closest("nav,main")))return a.tagName.toLowerCase()}
function normalize_href(a,b){var c={main:"art/",nav:"inx/"};return b.startsWith("../")?"/revo/"+b.substr(3):"/"==b[0]||b.startsWith("http")?b.startsWith("/cgi-bin/vokomail.pl")?"/revo/dlg/redaktilo.html?"+b.substring(b.search("art=")):b:"/revo/"+c[a]+b}
function load_page(a,b,c){c=void 0===c?!0:c;HTTPRequest("GET",b,{},function(f){var k=(new DOMParser).parseFromString(f,"text/html");f=document.getElementById("navigado");var q=document.querySelector("main");"nav"==a?(f.textContent="",f.append(k.querySelector("table"))):"main"==a&&(k=k.body,q.textContent="",q.append.apply(q,$jscomp.arrayFromIterable(k.children)),q.setAttribute("id","w:"+b),artikolo.preparu_art());c&&history.pushState({inx:f.firstElementChild.id,art:q.id},null,q.id.substring(2))})}
function navigate(a){var b=a.target.closest("a"),c=b.getAttribute("href");b=ref_target(b);"int"!=b&&(a.preventDefault(),"ext"==b?window.open(c):"main"==b?load_page(b,normalize_href(b,c)):"nav"==b&&load_page(b,normalize_href(b,c)))}function navigate_history(a){a=a.state;console.log(a);load_page("nav","/revo/inx/"+a.inx.substring(2)+".html",!1);load_page("main",a.art.substring(2),!1)}function load_xml(a){}function serchu(a){a.preventDefault()}
function restore_preferences(){redaktilo.restore_preferences();artikolo.restore_preferences()}window.onload=function(){restore_preferences();load_page("main","titolo.html");load_page("nav","../inx/_eo.html");document.body.addEventListener("click",navigate);window.addEventListener("popstate",navigate_history)};var js_sojlo=3,sec_art="s_artikolo",lingvoj_xml="../cfg/lingvoj.xml",MalkashEvento=new Event("malkashu",{bubbles:!0}),KomutEvento=new Event("komutu",{bubbles:!0});window.onload=function(){artikolo.restore_preferences();artikolo.preparu_art();artikolo.enkadrigu()};
window.onhashchange=function(){var a=getHashParts().mrk;if(a){var b=document.getElementById(a);b&&"H2"==b.tagName&&(b=b.closest("section").querySelector("div.kasxebla"));b?b.dispatchEvent(MalkashEvento):this.console.error("ne trovi\u011dis saltomarko '"+a+'"')}};
var artikolo=function(){function a(){var d=document.getElementsByClassName("kasxebla"),g=getHashParts().mrk,h=g?document.getElementById(g):null;h=h?h.closest("section.drv, section.fontoj").firstElementChild.id:null;var A=d.length>js_sojlo,z=!0;d=$jscomp.makeIterator(d);for(var m=d.next();!m.done;m=d.next())if(m=m.value,m.closest(".admin")&&0==m.childElementCount)m.closest(".admin").textContent="";else{m.addEventListener("malkashu",function(t){x(t.currentTarget);t.stopPropagation()});m.addEventListener("komutu",
function(t){var G=t.currentTarget.closest("section").querySelector("div.kasxebla");G.classList.contains("kasxita")?x(G):q(G);t.stopPropagation()});var u=H(m);u&&(u.classList.add("kashilo"),A&&g&&u.id!=h||!g&&!z?(u.appendChild(make_icon_button("i_mkash",null,"malka\u015du deriva\u0135on")),m.classList.add("kasxita")):u.appendChild(make_icon_button("i_kash",null,"ka\u015du deriva\u0135on")),z=!1,u.addEventListener("click",function(t){t.target.closest("section").querySelector("div.kasxebla").dispatchEvent(KomutEvento)}))}}
function b(){var d=document.getElementsByClassName("fontoj kasxita");d=$jscomp.makeIterator(d);for(var g=d.next();!g.done;g=d.next())g.value.addEventListener("malkashu",function(h){h.currentTarget.classList.remove("kasxita");h.stopPropagation()})}function c(){var d=document.getElementsByClassName("etendebla");d=$jscomp.makeIterator(d);for(var g=d.next();!g.done;g=d.next())if(g=g.value,g.classList.contains("tradukoj")){for(var h=void 0,A=!1,z=getHashParts().lng,m=$jscomp.makeIterator(g.children),u=
m.next();!u.done;u=m.next()){u=u.value;var t=u.getAttribute("lang");t&&("eo"==t?h=u:t!=z&&0>C.indexOf(t)?(h.classList.add("kasxita"),u.classList.add("kasxita"),A=!0):(h.classList.remove("kasxita"),u.classList.remove("kasxita")))}A&&!g.querySelector(".pli")&&(h=make_element("A",{lang:"eo",href:"#"},"pli..."),h.addEventListener("click",n),h.classList.add("pli","etendilo"),g.appendChild(h),1>Math.round((Date.now()-F)/864E5,0)&&(h=make_element("A",{lang:"eo",href:"#"},"preferoj..."),h.addEventListener("click",
v),h.classList.add("pref"),g.appendChild(make_element("SPAN")),g.appendChild(h)))}}function f(){for(var d=$jscomp.makeIterator(document.getElementsByClassName("kasxebla")),g=d.next();!g.done;g=d.next())g=g.value,(g.parentElement.classList.contains("drv")||g.parentElement.classList.contains("notoj"))&&q(g)}function k(){for(var d=$jscomp.makeIterator(document.getElementsByClassName("kasxebla")),g=d.next();!g.done;g=d.next())g=g.value,(g.parentElement.classList.contains("drv")||g.parentElement.classList.contains("notoj"))&&
x(g)}function q(d){d.classList.add("kasxita");(d=H(d))&&(d=d.querySelector(".i_kash"))&&d.classList.replace("i_kash","i_mkash")}function x(d){d.classList.remove("kasxita");(d=H(d))&&(d=d.querySelector(".i_mkash"))&&d.classList.replace("i_mkash","i_kash")}function n(d){d.preventDefault();d=d.target.parentElement;for(var g=$jscomp.makeIterator(d.children),h=g.next();!h.done;h=g.next())h.value.classList.remove("kasxita");(g=d.querySelector(".pli"))&&g.classList.add("kasxita");(g=d.querySelector(".pref"))&&
g.classList.add("kasxita")}function v(){var d=document.getElementById("pref_dlg"),g=[["a","b"],["c","g"],["h","j"],["k","l"],["m","o"],["p","s"],["t","z"]];if(d)d.classList.toggle("kasxita"),B();else{d=make_element("DIV",{id:"pref_dlg",class:"overlay"});var h=make_element("DIV",{id:"preferoj",class:"preferoj"}),A=make_button("preta",function(){document.getElementById("pref_dlg").classList.add("kasxita");B();c()},"fermu preferojn");A.setAttribute("id","pref_dlg_close");g=g.map(function(m){return{id:m.join("_"),
label:m.join("..")}});var z=make_element("DIV",{class:"ix_literoj"});I(z,"pref_lingvoj",null,g,w);z.appendChild(A);h.appendChild(z);h.appendChild(make_element("H3",{},"preferataj lingvoj"));h.appendChild(make_element("H3",{},"aldoneblaj lingvoj"));h.appendChild(make_element("UL",{id:"pref_lng"}));h.appendChild(make_element("UL",{id:"alia_lng"}));d.appendChild(h);document.getElementById(sec_art).getElementsByTagName("H1")[0].appendChild(d);y()}}function y(){HTTPRequest("GET",lingvoj_xml,{},function(){var d=
(new DOMParser).parseFromString(this.response,"text/xml"),g=document.getElementById("pref_lng"),h=document.getElementById("alia_lng"),A=document.getElementById("preferoj").querySelector('input[name="pref_lingvoj"]:checked').value.split("_"),z={};d=$jscomp.makeIterator(d.getElementsByTagName("lingvo"));for(var m=d.next();!m.done;m=d.next())if(e=m.value,m=e.attributes.kodo,"eo"!=m.value){var u=eo_ascii(e.textContent);z[u]={lc:m.value,ln:e.textContent}}d=$jscomp.makeIterator(Object.keys(z).sort());for(m=
d.next();!m.done;m=d.next()){l=m.value;m=z[l].lc;u=z[l].ln;var t=document.createElement("LI");t.setAttribute("data-lng",m);t.setAttribute("data-la",l);t.appendChild(document.createTextNode(u));0>C.indexOf(m)?(t.setAttribute("title","aldonu"),(u[0]<A[0]||u[0]>A[1])&&t.classList.add("kasxita"),h.appendChild(t)):(t.setAttribute("title","forigu"),g.appendChild(t),m=t.cloneNode(!0),m.setAttribute("class","kasxita"),h.appendChild(m))}h.addEventListener("click",D);g.addEventListener("click",E)})}function w(){for(var d=
document.getElementById("preferoj").querySelector('input[name="pref_lingvoj"]:checked').value.split("_"),g=$jscomp.makeIterator(document.getElementById("alia_lng").childNodes),h=g.next();!h.done;h=g.next())ch=h.value,h=ch.getAttribute("data-la"),h[0]<d[0]||h[0]>d[1]?ch.classList.add("kasxita"):ch.classList.remove("kasxita")}function D(d){d=d.target;if("LI"==d.tagName){var g=d.getAttribute("data-lng");g&&(C.push(g),F=Date.now());document.getElementById("pref_lng").appendChild(d.cloneNode(!0));d.classList.add("kasxita")}}
function E(d){d=d.target;if("LI"==d.tagName){var g=d.getAttribute("data-lng");if(g){var h=C.indexOf(g);C.splice(h,1)}d.parentElement.removeChild(d);ela=document.getElementById("alia_lng").querySelector("[data-lng='"+g+"'");ela.classList.remove("kasxita")}}function B(){if(0<C.length){var d={};d["w:preflng"]=C;d["w:prefdat"]=F;window.localStorage.setItem("revo_preferoj",JSON.stringify(d))}}function I(d,g,h,A,z){if(h){var m=document.createElement("LABEL");m.appendChild(document.createTextNode(h));d.appendChild(m)}h=
!0;A=$jscomp.makeIterator(A);for(m=A.next();!m.done;m=A.next()){r=m.value;m=document.createElement("SPAN");var u=h?make_element("INPUT",{name:g,type:"radio",id:r.id,checked:"checked",value:r.id}):make_element("INPUT",{name:g,type:"radio",id:r.id,value:r.id});h=!1;var t=make_element("LABEL",{for:r.id},r.label);m.appendChild(u);m.appendChild(t);d.appendChild(m)}z&&d.addEventListener("click",z)}function H(d){for(d=d.previousSibling;d&&"H2"!=d.nodeName;)d=d.previousSibling;return d}var C=[],F=Date.now();
return{restore_preferences:function(){var d=window.localStorage.getItem("revo_preferoj");d=d?JSON.parse(d):null;var g=navigator.languages||[navigator.language];C=d&&d["w:preflng"]?d["w:preflng"]:g.slice();F=d&&d["w:prefdat"]?d["w:prefdat"]:Date.now()},preparu_art:function(){if(document.getElementById(sec_art)){"file:"!=window.location.protocol&&(top.document.title="Reta Vortaro ["+document.getElementById(sec_art).getElementsByTagName("H1")[0].textContent.trim()+"]");document.getElementsByClassName("kasxebla");
a();b();c();var d=document.getElementsByTagName("article")[0],g=make_element("DIV",{id:"kash_btn"});g.appendChild(make_icon_button("i_kash_ch",f,"ka\u015du \u0109iujn deriva\u0135ojn"));g.appendChild(make_icon_button("i_mkash_ch",k,"malka\u015du \u0109iujn deriva\u0135ojn"));d.appendChild(g);if(d=document.body.getElementsByTagName("FOOTER")[0])if(d=d.querySelector("A"))g=make_element("A",{class:"redakto",href:"#",title:"agordu preferatajn lingvojn"},"preferoj"),g.addEventListener("click",v),d.insertAdjacentElement("afterend",
g),d.insertAdjacentText("afterend"," | ")}},enkadrigu:function(){if(0==document.getElementsByName("main").length){var d=make_element("main",{});d.append.apply(d,$jscomp.arrayFromIterable(document.body.children));document.body.appendChild(d)}if(0==document.getElementsByName("nav").length){d=make_element("nav",{});var g=make_element("div",{id:"navigado"});d.appendChild(g);document.body.prepend(d)}history.state&&history.state.inx&&(console.log(history.state),load_page("nav","/revo/inx/"+history.state.inx.substring(2)+
".html",!1))}}}();var redaktilo=function(){function a(n,v){this.url=v;this.xmlTag=n;this.codes={};this.fill=function(y){y=document.getElementById(y);for(item in this.codes){var w=item+" - "+this.codes[item];var D=document.createElement("option");w=document.createTextNode(w);D.appendChild(w);w=D;var E=item,B=document.createAttribute("value");B.value=E;w.setAttributeNode(B);y.appendChild(D)}};this.load=function(y){var w=this,D={};HTTPRequest("GET",this.url,{},function(){var E=(new DOMParser).parseFromString(this.response,
"text/xml");E=$jscomp.makeIterator(E.getElementsByTagName(w.xmlTag));for(var B=E.next();!B.done;B=E.next())e=B.value,D[e.attributes.kodo.value]=e.textContent;w.codes=D;y&&w.fill.call(w,y)})}}function b(){var n=window.localStorage.getItem("redaktilo_preferoj");if(n=n?JSON.parse(n):null){for(var v=$jscomp.makeIterator(["r:redaktanto","r:trdlng","r:klrtip","r:reftip","r:sxangxo"]),y=v.next();!y.done;y=v.next())key=y.value,document.getElementById(key).value=n[key];document.getElementById("r:cx").checked=
n["r:cx"]}}function c(){var n=getParamValue("art");n&&HTTPRequest("GET","/revo/xml/"+n+".xml",{},function(){document.getElementById("r:xmltxt").value=this.response;document.getElementById("r:art").value=n;var v=document.getElementById("r:art_titolo");v.textContent="\u00ab"+n+"\u00bb";v.setAttribute("href","/revo/art/"+n+".html");el=document.getElementById("r:xmltxt");el.setSelectionRange?(el.focus(),el.setSelectionRange(0,0)):el.createTextRange&&(v=el.createTextRange(),v.moveStart("character",0),
v.select());el.focus()})}function f(n,v,y){document.getElementById("r:xmltxt").focus();var w=document.getElementById("r:xmltxt");if(document.selection&&document.selection.createRange)v=document.selection.createRange(),v.moveEnd("character",n),v.moveStart("character",n),v.select(),v.scrollIntoView(!0);else if(w.selectionStart||"0"==w.selectionStart)w.selectionStart=n,w.selectionEnd=w.selectionStart,w.scrollTop=w.scrollHeight*v/y}var k=new a("lingvo","/revo/cfg/lingvoj.xml"),q=new a("fako","/revo/cfg/fakoj.xml"),
x=new a("stilo","/revo/cfg/stiloj.xml");ready(function(){document.getElementById("r:xmltxt")&&(f(0,0,1),b(),k.load(),q.load("r:sfak"),x.load("r:sstl"),c(),window.onbeforeunload=function(){for(var n={},v=$jscomp.makeIterator(["r:redaktanto","r:trdlng","r:klrtip","r:reftip","r:sxangxo"]),y=v.next();!y.done;y=v.next())key=y.value,n[key]=document.getElementById(key).value;n["r:cx"]=document.getElementById("r:cx").checked;window.localStorage.setItem("redaktilo_preferoj",JSON.stringify(n))})});return{restore_preferences:b}}();
